name: Running Karate Tests

permissions:
  contents: read  # Required for checkout

on:
  workflow_dispatch:  # allow manual runs too

  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'


jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      smoke: ${{ steps.smoke.outcome }}

    steps:
      # Checkout current repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Run smoke tests (gatekeeper)
      - name: Run smoke tests
        id: smoke
        run: mvn clean test -Psmoke

      # Run full tests ONLY if smoke passed
      - name: Run full test suite
        if: ${{ steps.smoke.outcome == 'success' }}  # Ensures it runs only if previous step passed
        run: mvn clean test -Pfull
        continue-on-error: true

      # Run performance tests ONLY if smoke passed
      - name: Run performance tests
        if: ${{ steps.smoke.outcome == 'success' }}  # Ensures it runs only if previous step passed
        run: mvn test -Pperf

      # Always generate merged report (even if tests failed)
      - name: Generated consolidated test report
        if: ${{ always() }}  # Ensures report is uploaded even if previous steps fail
        run: mvn test -Preport

      # Always upload report artifacts
      - name: Upload test evidence
        if: ${{ always() }}  # Ensures report is uploaded even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: test-evidence
          path: ./target/karate-merged-report/cucumber-html-reports/
