name: Running Karate Tests

permissions:
  contents: read  # Required for checkout

on:
  workflow_dispatch:  # allow manual runs too

  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'


jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      smoke: ${{ steps.smoke.outcome }}
      full: ${{ steps.full.outcome }}
      perf: ${{ steps.perf.outcome }}

    steps:
      # Checkout current repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Run smoke tests (gatekeeper)
      - name: Run smoke tests
        id: smoke
        run: mvn clean test -Psmoke

      # Run full tests ONLY if smoke passed
      - name: Run full test suite
        id: full
        if: ${{ steps.smoke.outcome == 'success' }}  # Ensures it runs only if previous step passed
        run: mvn clean test -Pfull
        continue-on-error: true

      # Run performance tests ONLY if smoke passed
      - name: Run performance tests
        id: perf
        if: ${{ steps.smoke.outcome == 'success' }}  # Ensures it runs only if previous step passed
        run: mvn test -Pperf
        continue-on-error: true

      # Always generate merged report (even if tests failed)
      - name: Generated consolidated test report
        if: ${{ always() }}  # Ensures report is uploaded even if previous steps fail
        run: mvn test -Preport

      # Always upload report artifacts
      - name: Upload test evidence
        if: ${{ always() }}  # Ensures report is uploaded even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: test-evidence
          path: ./target/karate-merged-report/cucumber-html-reports/

      # Fail pipeline if any test phase failed
      - name: Fail pipeline if tests failed
        if: ${{ always() }}
        run: |
          echo "Smoke outcome: ${{ steps.smoke.outcome }}"
          echo "Full outcome:  ${{ steps.full.outcome }}"
          echo "Perf outcome:  ${{ steps.perf.outcome }}"

          if [ "${{ steps.smoke.outcome }}" != "success" ]; then
            echo "Smoke tests failed"
            exit 1
          fi

          if [ "${{ steps.full.outcome }}" == "failure" ]; then
            echo "Full test suite failed"
            exit 1
          fi

          if [ "${{ steps.perf.outcome }}" == "failure" ]; then
            echo "Performance tests failed"
            exit 1
          fi

          echo "All test phases passed"
